### ISSUE TITLE
[1.16] Gas duping using gas nodes from Laser Relays

### ISSUE THREAD

**Issue by NielsPilgaard** [Tfarcenim/Laser-Relays#1]
Original report: https://github.com/NillerMedDild/Enigmatica5/issues/442

Steps to reproduce: connect to gas tanks, one filled with a gas, and other empty, link them with gas nodes from laser relays.
the gas seems to be inserting at the output, but not draining the input

`laserrelays-1.6`

**Comment by Tfarcenim** [comment]
fixed in 1.7
