### ISSUE TITLE
Crash after the splash screen

### ISSUE THREAD

**Issue by Zemogiter** [Tfarcenim/Laser-Relays#2]
list of mods:
absentbydesign-1.16.2-1.1.0.jar
anviltweaks-3.0.jar
automaticdoors_1.16.2-1.4.jar
balancedenchanting-1.0.jar
bedspreads-forge-1.16.2-5.0.0.0.jar
caelus-forge-1.16.2-2.0.0.0.jar
collective-1.16.2-1.38.jar
corpse-1.16.2-1.0.6.jar
curios-forge-1.16.2-4.0.0.0.jar
curiouselytra-forge-1.16.2-4.0.0.0.jar
curiousshulkerboxes-forge-1.16.2-4.0.0.0.jar
cyclepaintings_1.16.2-1.3.jar
dankstorage-3.9.jar
dismountentity_1.16.2-1.2.jar
doubledoors_1.16.2-2.1.jar
dragondropselytra_1.16.2-1.1.jar
durability101-1.16-0.0.3.jar
extendedbonemeal_1.16.2-1.1.jar
extraanvils-4.0.jar
forge-curioofundying-1.16.2-5.0.0.0.jar
globalxp-1.16.2-v1.4.13.jar
grindstonesharpertools_1.16.2-1.4.jar
healingcf_1.16.2-2.3.jar
horsestandstill-1.16.2-1.0.1.jar
humblingbundle_1.16.2-1.3.jar
ironelytra-1.3a-1.16.2.jar
jei-1.16.2-7.1.0.11.jar
kelpfertilizer_1.16.2-1.1.jar
laserrelays-1.7.jar
MixinBootstrap-1.0.3.jar

[latest.log](https://github.com/Tfarcenim/Laser-Relays/files/5102439/latest.log)

**Comment by Darkere** [comment]
The mod has an accidental Mekanism dependency. Installing it would solve it (if you want to).

**Comment by Tfarcenim** [comment]
fixed in 1.8-1.16.2
