### ISSUE TITLE
Laser Relays seems to cause Render Leak

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [Tfarcenim/Laser-Relays#3]
MC 1.16.1, version 1.7

Originally noticed this in conjunction with Mining Gadgets (see https://github.com/Direwolf20-MC/MiningGadgets/issues/109), however I'm pretty sure that something in your render pipeline is causing a render leak, which causes certain other mods (such as Mining Gadgets) to stop displaying graphical effects and overlays correctly.

Since I was unable to reproduce the original issue without Laser Relays installed, I am pretty certain that your mod **is** actually the culprit in the original issue as well, however unfortunately, I'm not quite sure where exactly the problem might lie here

**Comment by Tfarcenim** [comment]
this is the last time I use renderworldlastevent" mixin time

**Comment by Tfarcenim** [comment]
fixed in 1.8-1.16.2
![2020-09-07_16 02 27](https://user-images.githubusercontent.com/44327798/92414744-a275cd00-f123-11ea-8e87-46f7fdeff886.png)
